### ISSUE TITLE
Access external URLs

### ISSUE THREAD

**Issue by nalgeon** [nalgeon/pokitoki#10]
When you ask ChatGPT about external resources, it either hallucinates:

> Q: Explain https://sqlime.org/employees.sql?
>
> A: The employees table appears to have columns such as employee_id, first_name, last_name, email, phone_number, hire_date, job_id, salary, commission_pct, manager_id, and department_id.

Or acknowledges that it doesn't have access to remote URLs:

> Q: What is the content of https://sqlime.org/employees.sql? Make no assumptions.
>
> A: As an AI language model, I cannot access external URLs on the internet.

We can probably fix this by fetching the external content and feeding it to the model.

**Comment by HeySlava** [comment]
What would be the expected response if a single request to OpenAI exceeds the content limit (a long article)?

**Comment by nalgeon** [comment]
It would be an error returned by the OpenAI API.

**Comment by HeySlava** [comment]
I agree. However it's possible to split a text into several requests

**Comment by nalgeon** [comment]
The `max_tokens` parameter in `openai.ChatCompletion` is the maximum number of tokens to generate (the number of output tokens). It's currently hardcoded to 1000.

The number of input tokens is determined by the user message. After replacing the URLs with their content, it could be significant.

OpenAI has a limit on the total number of tokens (prompt + input + output). It will return an error if there are too many tokens.

All of this is beyond the scope of this issue. Handling large numbers of tokens is important, but that's a question for another time.

**Comment by nalgeon** [comment]
Here goes: [External links](https://github.com/nalgeon/pokitoki#external-links)

**Comment by HeySlava** [comment]
```python
    def is_text(self) -> bool:
        """Checks if the content type is plain text."""
        if not self.content_type:
            return False
        if self.content_type.startswith("text/"):
            return True
        if self.content_type in self.allowed_content_types:
            return True
        return False
```

Isn't it better to raise an exception instead of returning `False`? My idea is simple: users will understand that their links are unprocessable before request to Openai.

**Comment by nalgeon** [comment]
I prefer the current implementation. The bot states that it can't process the binary content:

> Q: Explain this paper in simple terms https://arxiv.org/pdf/1706.03762.pdf
>
> A: I'm sorry, but I cannot access the contents of the paper you provided as it appears to be unknown binary content. Can you please provide me with the correct link or the title of the paper so I can provide you with a clear explanation?

**Comment by HeySlava** [comment]
This is my example: 
> Read the most popular comments: https://www.youtube.com/watch?v=outcGtbnMuQ
> I apologize, but the content you provided does not include any comments from viewers. Can you please provide a different link or specify where the comments can be found?

**Comment by nalgeon** [comment]
This is another case. The content type is OK (text/html), but the actual content is loaded dynamically via JS. I don't think I will support such cases.

**Comment by nalgeon** [comment]
I'm pretty happy with with the implementation so far.
