### ISSUE TITLE
The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by Anzic23** [nalgeon/pokitoki#11]
In the configuration, I specified GPT-4, but the bot returned the following response:
Failed to answer. Reason: openai.error.InvalidRequestError: The model: `gpt-4` does not exist

**Comment by nalgeon** [comment]
That's because you don't have access to OpenAI's GPT-4 API. It's not public yet and only available by invitation.

You can join the [waitlist](https://openai.com/waitlist/gpt-4-api) or wait for the public release.
