### ISSUE TITLE
Image generation

### ISSUE THREAD

**Issue by nalgeon** [nalgeon/pokitoki#13]
Create an image with the `/imagine` command, e.g:

```
/imagine lazy cat on a sunny day
```

Use the DALL-E 2 model from OpenAI.

**Comment by HeySlava** [comment]
What are your thoughts on parameters?

Should they be hardcoded or retrieved from a configuration file?

If they are hardcoded, what is the optimal number and size of images?

I think that `n=1` and `size=512x512` is a good starting point

**Comment by nalgeon** [comment]
The feature is ready to try in v99, see the [docs](https://github.com/nalgeon/pokitoki#image-generation). The default `size` is 512×512, but can be changed in the image description. `n` is hardcoded to 1.
