### ISSUE TITLE
`config` telegram.token property problem

### ISSUE THREAD

**Issue by HeySlava** [nalgeon/pokitoki#16]
Seems like bug:
![image](https://user-images.githubusercontent.com/69298864/230797713-08c3bab2-7be0-4bd3-bb40-f392f8bee74e.png)

How to reproduce:

1) change token property
2) restart your bot

The bot won't work anymore

**Comment by nalgeon** [comment]
You have changed the token to an invalid value. How could the bot work after that?

**Comment by HeySlava** [comment]
I can't imagine situation where I might need to change the token on the fly. I would prevent this behavior at all

**Comment by nalgeon** [comment]
`/config` is an admin-only command. True, you can totally shoot yourself in the foot with it. Just don't do it.

**Comment by HeySlava** [comment]
Why don't you want to have this property read only?

**Comment by nalgeon** [comment]
Because the whole point of the `/config` feature is to provide a means to edit all settings.

**Comment by nalgeon** [comment]
The only read-only properties are those that the admin is not supposed to change under any circumstances (like `version`). Everything in `config.yml` is editable.
