### ISSUE TITLE
Allow streaming response

### ISSUE THREAD

**Issue by dit7ya** [nalgeon/pokitoki#27]
Thanks for this project - some pretty cool ideas in here. 

It would be helpful to have streaming responses from the bot (with Telegram message edits). https://github.com/n3d1117/chatgpt-telegram-bot has this feature, for example.

**Comment by nalgeon** [comment]
Thanks! I tried the streaming feature and didn't like it that much. And it's quite a headache to implement. So I'll pass, sorry.
