### ISSUE TITLE
update openai>=1.3.0 to support OPENAI_BASE_URL environment variable

### ISSUE THREAD

**Issue by tandav** [nalgeon/pokitoki#34]
Hi, thank you for great project. It would be nice to update openai to `>=1.3.0`. It [support base_url setting](https://github.com/openai/openai-python/releases/tag/v1.3.0) via argument to client or via `OPENAI_BASE_URL` environment variable.

This setting allows to use openai api proxy and access openai api if it's blocked. For example, someone can set:

```py
os.environ['OPENAI_BASE_URL'] = 'https://openai-proxy.company.com/v1'
```
And use it if default api url `https://api.openai.com/v1` is blocked, or giving some cloudflare errors.

**Comment by nalgeon** [comment]
Updated `openai` to `1.3.3`.
