### ISSUE TITLE
"Message is too long"

### ISSUE THREAD

**Issue by TimofeyTishkin** [nalgeon/pokitoki#36]
Hi, I've just followed every step of the Setup paragraph and the bot says it's too long literally for every message except commands. 
Any ideas why this happens? Please help...
![IMG_20240126_192658_883](https://github.com/nalgeon/pokitoki/assets/75540392/48337750-2460-45c3-9fd7-da90af65603f)

**Comment by nalgeon** [comment]
There is probably something wrong with config, and the exception text you get is too long for Telegram to display, so you get "message is too long" instead of the actual error. If you update to the latest revision, you'll (hopefully) see the actual error now.

**Comment by TimofeyTishkin** [comment]
Thanks! It worked, and the real problem is "openai.PermissionDeniedError". Says it's because API key os incorrect. Is it not okay to use personal key?

**Comment by nalgeon** [comment]
No idea :)

**Comment by nalgeon** [comment]
Possible reasons I can think of:

- You are not using a valid key from https://platform.openai.com/account/api-keys
- You've set permissions other than "All" for your API key.
- Your server is located in a country that is not allowed by OpenAI.

In any case, the problem is not with the bot itself.
