### ISSUE TITLE
The bot works in groups and chats not included in the list /config telegram.chat_ids

### ISSUE THREAD

**Issue by BollexN1** [nalgeon/pokitoki#37]
Good afternoon. I have encountered the fact that the bot works in any group and answers questions of any user in private chats when two IDs are specified in the list of groups.
In the instructions to the bot I have not found a description of the correct configuration settings in terms of specifying chat_ids. 
At the request /config telegram bot shows the following information:
{'token': 'mytoken', 'usernames': [], 'admins': ['1', '2'], 'chat_ids': ['10-character ID', '10-character ID']}
Please explain how to set the chat_ids so that the bot only works in the groups I want.

**Comment by nalgeon** [comment]
Hi! Be sure to add yourself to the `telegram.usernames` config property, otherwise the bot will be available to everyone.
