### ISSUE TITLE
Bot does not respond to group users not included in the userlist

### ISSUE THREAD

**Issue by BollexN1** [nalgeon/pokitoki#38]
Dear Developer.
I have filled in the config telegram section as follows:
/config telegram
{'token': 'my_token', 'usernames': ['a', 'b'], 'admins': ['a', 'b'], 'chat_ids': [1, 2]}

With this setting, the bot does not answer questions from all group members, only from users in the list (same as admins list).
Both groups are closed (not public).
To make the bot respond to all members of a group I have to clear the list of users, but then the bot starts responding to any telegram user outside of the groups set in the config.
What am I doing wrong?
I need my bot works same as @Marika_tgbot))

**Comment by nalgeon** [comment]
The only reason I can think of is that the `chat_ids` are incorrect (i.e. these are not the actual IDs of your groups).

**Comment by nalgeon** [comment]
Group IDs start with `-100`. The `version` command shows them when run in the group.

**Comment by BollexN1** [comment]
> Group IDs start with `-100`. The `version` command shows them when run in the group.

Thank you for the clarification. Indeed, my mistake, I didn't take into account the information from the /version command.
Thanks again for the great development.

**Comment by nalgeon** [comment]
Sure!
