### ISSUE TITLE
admin panel

### ISSUE THREAD

**Issue by HeySlava** [nalgeon/pokitoki#4]
Hi!

Is is interesting for you if I add an admin's panel?

It will be for new users. Currently, you add them manually in config.

How I see it:

Add /users command. It will be available only for admin

```
/users add @some_user
/users drop @some_user
/users list
```

**Comment by nalgeon** [comment]
I'd rather not. I try to keep the bot as simple as possible.

**Comment by nalgeon** [comment]
I've added the [`/config`](https://github.com/nalgeon/pokitoki#configuration) command in v129 to edit settings on the fly.
