### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by repen** [nalgeon/pokitoki#40]
Hello. The command `python -m bot.bot` can be transformed into `python -m bot`. How to do this? Move the code from `bot/bot.py` to `bot/__main__.py`

https://github.com/nalgeon/pokitoki/blob/791af627c557be56a05cb5bda3efe6a433464f41/README.md?plain=1#L310

**Comment by nalgeon** [comment]
Thanks for the suggestion! I like it the way it is.
