### ISSUE TITLE
PermissionDeniedError: Error code: 403

### ISSUE THREAD

**Issue by Anzic23** [nalgeon/pokitoki#42]
When communicating with the bot, the following message appears:
`openai.PermissionDeniedError: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
`

**Comment by nalgeon** [comment]
As the error says, your country is blocked in OpenAI. This has nothing to do with the bot.
